      SUBROUTINE CPUSEC (T)
C     *
C     ROUTINE FOR TIMING (CPU TIME IN SECONDS).
C     *
      DOUBLE PRECISION T
CUNIX VERSION FOR UNIX MACHINES WHICH PROVIDE A LIBRARY FUNCTION ETIME.
c     c REAL ETIME,TARRAY,TOTAL
c       DIMENSION TARRAY(2)
c       TTOTAL = ETIME(TARRAY)
c       T      = TARRAY(1)
CIBM  VERSION FOR IBM RS/6000 WHICH PROVIDES A LIBRARY FUNCTION MCLOCK.
      INTEGER I
        I      = MCLOCK()
        T      = I/100.0D0
CRAY  VERSION FOR CRAY WHICH PROVIDES A LIBRARY ROUTINE SECOND.
C     CALL SECOND(T)
CNEC  VERSION FOR NEC WHICH PROVIDES A LIBRARY ROUTINE CLOCK.
C     CALL CLOCK(T)
CSNI  VERSION FOR SNI-FUJITSU WHICH PROVIDES A LIBRARY ROUTINE CLOCK.
C     CALL CLOCK(T,0,2)
CONV  VERSION FOR CONVEX WHICH PROVIDES A VECLIB FUNCTION CPUTIME.
C     REAL CPUTIME
C     T      = CPUTIME(0.0)
      RETURN
      END
