#!/bin/ksh
#PBS -A ARLAP23623C5L 
#PBS -l walltime=00:30:00
#PBS -l ncpus=1
#PBS -q debug

#PBS -N unia-scf256
#PBS -o mp2e1.e1.out
#PBS -e mp2e1.e1.err
cd /work/detaylor/MD/my-md/INTERFACE/ARL-MD-flexible-develop-3pressure/src/
module load PrgEnv-pgi/3.1.61
make

